### PR TITLE
MGMT-2213,MGMT-2380 Bring back split into registration and next step

### PR DESCRIPTION
**Pull request by empovit**
The agent systemd service has been changed to only register its host with assisted service. The service replies with a command for running the core part of the agent as a container, so that its image is always up to date. This core part polls for next steps and posts replies as before. 

Also, README has been updated and cleaned up.

### CODE REVIEW

**Review by osherdp — APPROVED** [review]

**Review by ori-amizur — COMMENTED** [review]
/approve
/lgtm

**Pull request merged**
