### PR TITLE
MGMT-9358 update assisted-service after split to submodules

### PR DESCRIPTION
**Pull request by filanov**
Require to update golang to 1.17
Reduce replaces for k8s packages

### CODE REVIEW

**Comment by filanov** [comment]
/hold
Need to replace release repo as well

**Comment by filanov** [comment]
release pr https://github.com/openshift/release/pull/26890

**Comment by filanov** [comment]
/retest
Looks like an issue after the rebase

**Comment by filanov** [comment]
all the jobs passed locally can it be related to https://github.com/openshift/release/pull/26890 not being merged?

**Comment by osherdp** [comment]
> all the jobs passed locally can it be related to [openshift/release#26890](https://github.com/openshift/release/pull/26890) not being merged?

yes, it seems related

**Comment by filanov** [comment]
/retest
pr to release was merged.

**Comment by filanov** [comment]
because of an issue with how the ci works i split this pr
1. https://github.com/openshift/assisted-installer-agent/pull/308 update golang version of the docker files, ci will still use 1.16
2. update release to use golang 1.17
3. push this PR.

**Review by osherdp — APPROVED** [review]

**Pull request merged**
