### PR TITLE
MGMT-1680 Adds discovery_agent_version header to agent API calls

### PR DESCRIPTION
**Pull request by nmagnezi**

### CODE REVIEW

**Comment by nmagnezi** [comment]
cc: @avishayt

**Comment by nmagnezi** [comment]
This PR is expected to fail in CI until we merge https://github.com/openshift/assisted-service/pull/179.
However, tested locally using debug prints on assisted-service and the header is sent as expected:

`
time="2020-08-26T08:26:47Z" level=info msg="NIR DEBUG: incoming request details: {POST /api/assisted-install/v1/clusters/8a5f4eb5-3703-48a9-bbd2-36697fb722f6/hosts/5ba2b202-8d51-4b93-92d6-9fa7e56f2ea4/instructions HTTP/1.1 1 1 map[Accept:[application/json] Accept-Encoding:[gzip] Content-Length:[1874] Content-Type:[application/json] Discovery_agent_version:[quay.io/nmagnezi/assisted-installer-agent:agent_ver10] User-Agent:[Go-http-client/1.1] X-Request-Id:[f967c4ec-df3c-42fc-9455-0ba2db76cc9a] X-Secret-Key:[<removed>]] 0xc000c006c0 <nil> 1874 [] false 10.1.8.35:6000 map[] map[] <nil> map[] 172.17.0.1:56649 /api/assisted-install/v1/clusters/8a5f4eb5-3703-48a9-bbd2-36697fb722f6/hosts/5ba2b202-8d51-4b93-92d6-9fa7e56f2ea4/instructions <nil> <nil> <nil> 0xc0004985d0}" func="github.com/openshift/assisted-service/pkg/auth.(*AuthHandler).CreateAuthenticator.func1.2" file="/go/src/github.com/openshift/origin/pkg/auth/auth_handler.go:223" pkg=auth
`

**Comment by nmagnezi** [comment]
Tested with test-infra:

captured a POST from the `agent` to `assisted-service` ==> `Discovery_agent_version:[agent_ver21]`
```
time="2020-08-27T11:03:20Z" level=info msg="NIR DEBUG request: {POST /api/assisted-install/v1/clusters/8630bf6a-9495-49c1-8e4d-be4bb19fe0f6/hosts/efacb17c-7b64-4837-ad78-a13aac0fc6b3/instructions HTTP/1.1 1 1 map[Accept:[application/json] Accept-Encoding:[gzip] Content-Length:[95879] Content-Type:[application/json] Discovery_agent_version:[agent_ver21] User-Agent:[Go-http-client/1.1] X-Request-Id:[f3ae3cdc-fdc1-4334-934d-280c87836f0f] X-Secret-Key:[b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K25tYWduZXppcmVkaGF0Y29tMW90NXVxZ2Vrb3RhdGVqZ2MwcnI0ZnljcmNnOlFTUEdOS1RGMTc2WU9KR0E2MzMzWEtYVUhaWUxVT0VRSUdFWlZJQTdOMU1RVE9GTVBTRTJNRjg5MlVIMkpPRUI=]] 0xc00123a240 <nil> 95879 [] false 10.1.8.35:6000 map[] map[] <nil> map[] 172.17.0.1:35693 /api/assisted-install/v1/clusters/8630bf6a-9495-49c1-8e4d-be4bb19fe0f6/hosts/efacb17c-7b64-4837-ad78-a13aac0fc6b3/instructions <nil> <nil> <nil> 0xc0010c8c90}" func="github.com/openshift/assisted-service/pkg/auth.(*AuthHandler).CreateAuthenticator.func1.2" file="/go/src/github.com/openshift/origin/pkg/auth/auth_handler.go:222" pkg=auth
```

Captured from `assisted-service` metrics API ==> `discoveryAgentVersion="agent_ver21"`
```
curl `minikube ip`:32713/metrics | grep -i assisted_installer_host_installation_phase_seconds

service_assisted_installer_host_installation_phase_seconds Histogram/sum/count of time for each phase, by phase, final install result, and OCP version
# TYPE service_assisted_installer_host_installation_phase_seconds histogram
service_assisted_installer_host_installation_phase_seconds_bucket{discoveryAgentVersion="agent_ver21",openshiftVersion="4.5",phase="Configuring",result="Done",le="0.005"} 0
service_assisted_installer_host_installation_phase_seconds_bucket{discoveryAgentVersion="agent_ver21",openshiftVersion="4.5",phase="Configuring",result="Done",le="0.01"} 0
service_assisted_installer_host_installation_phase_seconds_bucket{discoveryAgentVersion="agent_ver21",openshiftVersion="4.5",phase="Configuring",result="Done",le="0.025"} 0
service_assisted_installer_host_installation_phase_seconds_bucket{discoveryAgentVersion="agent_ver21",openshiftVersion="4.5",phase="Configuring",result="Done",le="0.05"} 0
```

**Review by avishayt — APPROVED** [review]

**Pull request merged**
