### PR TITLE
Add FOCUS env parameter to skipper.yaml

### PR DESCRIPTION
**Pull request by rollandf**

### CODE REVIEW

**Comment by rollandf** [comment]
@ori-amizur

**Comment by nmagnezi** [comment]
On-par with [this](https://github.com/openshift/assisted-service/commit/54d56712b59d306125ee68d2014c98cf1e995e75#diff-f4abcdd4f413d4c0698332943e99e13dR24), looks good.
Please also add this to [README](https://github.com/openshift/assisted-installer-agent#testing) so users are aware of it.

**Comment by rollandf** [comment]
> On-par with [this](https://github.com/openshift/assisted-service/commit/54d56712b59d306125ee68d2014c98cf1e995e75#diff-f4abcdd4f413d4c0698332943e99e13dR24), looks good.
> Please also add this to [README](https://github.com/openshift/assisted-installer-agent#testing) so users are aware of it.

Done

**Review by nmagnezi — COMMENTED** [review]
/lgtm

**Review by YuviGold — APPROVED** [review]

**Pull request merged**
