### PR TITLE
NO-ISSUE: fix dependabot update

### PR DESCRIPTION
**Pull request by eifrach**

### CODE REVIEW

**Comment by eifrach** [comment]
> @eifrach Was `ghw.MemoryInfo` name was changed to `ghw.MemoryArea` in `ghw` update that was made by dependabot ?

yes, the name was changed and which breaks in the new version

**Comment by filanov** [comment]
To avoid most lint issues i suggest to add a file watcher to your editor, it will automatically fix most of the lint issues for you

**Review by filanov — APPROVED** [review]

**Pull request merged**
