### PR TITLE
MGMT-2347: trim the free-addresses message

### PR DESCRIPTION
**Pull request by osherdp**
```
> exit-code <255>Sending step <free-addresses> reply output <[{"free_addresses...> error <> exit-code <0>Sending step <free-addresses> reply output <> error <nmap: Target.cc:503: void Target::stopTimeOutClock(const timeval*): Assertion `htn.toclock_running == true' failed.
```

### CODE REVIEW

**Comment by YuviGold** [comment]
Unfortunately message like `<[{"free_addresses...>` doesn't tell anything..
In addition I think it would make us problems with logger parsers while there's only an opening double-quotes  without the closing ones.

I would appreciate if the list of free-addresses could be grouped into ranges as I suggested in the ticket.
Best case - The range would have 1 item.
Worst case - The range would be decreased by half.
In this scenario the message would be still informative and readable.

**Comment by osherdp** [comment]
> Unfortunately message like `<[{"free_addresses...>` doesn't tell anything..
> In addition I think it would make us problems with logger parsers while there's only an opening double-quotes without the closing ones.
> 
> I would appreciate if the list of free-addresses could be grouped into ranges as I suggested in the ticket.
> Best case - The range would have 1 item.
> Worst case - The range would be decreased by half.
> In this scenario the message would be still informative and readable.

BTW logging the count of the addresses is not enough?
I'm not afraid from implementing the ranges solution, I just want to state that it seems like a bit of an overkill solution for a log message

**Comment by YuviGold** [comment]
> > Unfortunately message like `<[{"free_addresses...>` doesn't tell anything..
> > In addition I think it would make us problems with logger parsers while there's only an opening double-quotes without the closing ones.
> > I would appreciate if the list of free-addresses could be grouped into ranges as I suggested in the ticket.
> > Best case - The range would have 1 item.
> > Worst case - The range would be decreased by half.
> > In this scenario the message would be still informative and readable.
> 
> BTW logging the count of the addresses is not enough?
> I'm not afraid from implementing the ranges solution, I just want to state that it seems like a bit of an overkill solution for a log message

I agree that it is a bit of an overkill just in logging perspective. I was thinking it should be also the data structure communicating with the assisted-service to reduce the traffic size (this list is being sent a lot of times).
@ori-amizur said that this method wasn't picked, I don't remember why. Ori, can you elaborate?

About a counter - Although I still prefer the ranges one, the counter would be a satisfying clear solution.

**Comment by osherdp** [comment]
@ori-amizur and I talked about it yesterday
I also thought we're going to change it on the API level, but it's a major change of API which shouldn't be made without a good reason
Most importantly the API might change in the future to include assigned-addresses as opposed to free-addresses, as the assigned addresses are acquired by entities that may have other interesting information

**Review by YuviGold — APPROVED** [review]
LGTM

**Comment by YuviGold** [comment]
> /hold

@osherdp  Why is this on hold?

**Pull request merged**
