### PR TITLE
NO-ISSUE - Upgrade assisted-service to latest version

### PR DESCRIPTION
**Pull request by omertuc**
Had to also add a bunch of replace directives, see this for more info: https://github.com/golang/go/issues/30354

### CODE REVIEW

**Comment by filanov** [comment]
@carbonin maybe we can start with sub modules in assisted service instead of hive?

**Comment by omertuc** [comment]
/hold

This doesn't work. Still a lot of conflicts

**Comment by carbonin** [comment]
Maybe, what pieces of the service is the agent depending on?

**Comment by filanov** [comment]
> Maybe, what pieces of the service is the agent depending on?

The auto generated parts. 
```
github.com/openshift/assisted-service/client/installer
github.com/openshift/assisted-service/models
```

**Comment by carbonin** [comment]
Got it:
```
08:24:23:~/Source/assisted-installer-agent (master)$ git grep github.com/openshift/assisted-service | cut -d: -f3 | sort | uniq
	"github.com/openshift/assisted-service/client"
	"github.com/openshift/assisted-service/client/installer"
	"github.com/openshift/assisted-service/models"
	"github.com/openshift/assisted-service/pkg/auth"
	"github.com/openshift/assisted-service/pkg/requestid"
```

**Comment by carbonin** [comment]
Yeah, I'll give it a shot today

**Comment by omertuc** [comment]
Irrelevant

**Pull request closed without merging**
