### PR TITLE
Bug 2081282: Implementing new service-agent protocol on agent side - backport of MGMT-7530

### PR DESCRIPTION
**Pull request by tsorya**
Aggregation of couple of PRs for backport

https://issues.redhat.com/browse/MGMT-7530

https://github.com/openshift/assisted-installer-agent/pull/295
https://github.com/openshift/assisted-installer-agent/pull/315
https://github.com/openshift/assisted-installer-agent/pull/316

### CODE REVIEW

**Comment by tsorya** [comment]
/retitle Bug 2081282: Implementing new service-agent protocol on agent side

**Comment by omertuc** [comment]
Can you emphasize in the title that this is a backport?

**Comment by tsorya** [comment]
@omertuc this is couple of PRs

**Review by filanov — APPROVED** [review]

**Pull request merged**
