### PR TITLE
AGENT-594: remove agent based installer code

### PR DESCRIPTION
**Pull request by andfasano**
This patch removes all the code (and vendored dependencies) related to the agent-based installer (to ship the agent-tui).

Requires https://github.com/openshift/release/pull/40513 (where the CI part was cleaned up)

### CODE REVIEW

**Comment by andfasano** [comment]
/assign @osherdp 

https://github.com/openshift/release/pull/40513 landed, so we could proceed with this PR now

**Review by osherdp — APPROVED** [review]

**Pull request merged**
