### PR TITLE
MGMT-3033 - Populating S.M.A.R.T. field in inventory host disks

### PR DESCRIPTION
**Pull request by omertuc**
- Updated assisted service to latest version
- Using smartctl to populate the Smart field in inventory host disks
- Organized disks_test.go a bit

### CODE REVIEW

**Comment by rollandf** [comment]
@omertuc this PR requires a new tool for the agent.
Please make sure that downstream image is able to install it.

**Comment by omertuc** [comment]
> @omertuc this PR requires a new tool for the agent.
> Please make sure that downstream image is able to install it.

Isn't that what the `downstream-change-needed` label is for? No need to hold, it's already blocking.
And in that case, @gamli75 told me I should first merge on GitHub and only then change on Gerrit, the label is here just to remind me to do that.

Or are you talking about something else?

**Comment by rollandf** [comment]
I forgot the label is already blocking.
I meant that you should make sure the this tool will be available, otherwise this patch will not work.
You can make the check downstream before that this PR is merged.

**Comment by omertuc** [comment]
> I meant that you should make sure the this tool will be available, otherwise this patch will not work.
> You can make the check downstream before that this PR is merged.

Available in what sense? I've added it to the Dockerfile in this repo (smartmontools package includes smartctl). Once it's merged I'll also add it to the gerrit per Liat's instructions (she said I should first merge it here).

**Comment by rollandf** [comment]
> > I meant that you should make sure the this tool will be available, otherwise this patch will not work.
> > You can make the check downstream before that this PR is merged.
> 
> Available in what sense? I've added it to the Dockerfile in this repo (smartmontools package includes smartctl). Once it's merged I'll also add it to the gerrit per Liat's instructions (she said I should first merge it here).

The base image is different. In downstream we use openshift/ose-base:ubi8 and I don't know if `smartmontools` is available to be installed by default in this image.

**Comment by omertuc** [comment]
> > > I meant that you should make sure the this tool will be available, otherwise this patch will not work.
> > > You can make the check downstream before that this PR is merged.
> > 
> > 
> > Available in what sense? I've added it to the Dockerfile in this repo (smartmontools package includes smartctl). Once it's merged I'll also add it to the gerrit per Liat's instructions (she said I should first merge it here).
> 
> The base image is different. In downstream we use openshift/ose-base:ubi8 and I don't know if `smartmontools` is available to be installed by default in this image.

Gerrit CI finished successfully, so I guess it's fine

**Pull request merged**
