### PR TITLE
[release-ocm-2.4] MGMT-9886: bump assisted-service version

### PR DESCRIPTION
**Pull request by danielerez**

### CODE REVIEW

**Review by filanov — APPROVED** [review]

**Comment by filanov** [comment]
/lgtm cancel 
how can we update to master? didn't we remove v1 apis there?

**Comment by danielerez** [comment]
> /lgtm cancel how can we update to master? didn't we remove v1 apis there?

it's not using service from master. Updated to the latest 2.4: https://github.com/openshift/assisted-service/commit/26759e104e8a915ccaa33892f948bb8015d8b187

**Review by osherdp — APPROVED** [review]

**Comment by danielerez** [comment]
/hold
missing bz

**Pull request merged**
